<?php 

class Costeo
{


function __construct()
{

}



function lista_costeo_mensual($fechainicio='',$fechafin='')
{
$conexion =  new Conexion();
$conexion -> sqlserver();
$query  =  "
SELECT D.OT,D.OT+'-'+CONVERT(VARCHAR,D.SUB_OT)AS SUB_OT,D.CODIGO,M.ADESCRI,D.NOTA_INGRESO,D.STATUS,D.TIPO_OT,D.TIPO_PROCESO,D.FECHA_INICIO,D.FECHA_FIN,
D.CANTIDAD,D.ENTREGA,D.SALDO,ISNULL(CONSUMOS.CANTIDAD,0) AS COSTO_TOTAL_CONSUMOS,
ISNULL(CONSUMOS.CANTIDAD,0)/ ISNULL(D.ENTREGA,0) AS COSTO_UNITARIO_CONSUMOS,
ISNULL(SERVICIOS.CANTIDAD,0) AS COSTO_TOTAL_SERVICIOS,
ISNULL(SERVICIOS.CANTIDAD,0)/ ISNULL(D.ENTREGA,0) AS COSTO_UNITARIO_SERVICIOS
FROM [BD_COSTOS].DBO.DETALLE_OT AS  D  
INNER JOIN  [010BDCOMUN].DBO.MAEART AS M ON
D.CODIGO=M.ACODIGO
LEFT JOIN (SELECT SUB_OT,SUM(DECANTID)AS CANTIDAD FROM [BD_COSTOS].DBO.DETALLE_CONSUMOS  AS DC INNER JOIN
(SELECT  DENUMDOC,DEITEM,DECODIGO,DEDESCRI,DECANTID,DEPRECIO FROM [010BDCOMUN].DBO.MOVALMDET WHERE DETD='NS' AND DEALMA='01') AS NS
ON DC.NOTA_SALIDA=NS.DENUMDOC AND DC.ITEM=NS.DEITEM
GROUP BY SUB_OT
)AS CONSUMOS  ON D.OT+'-'+CONVERT(VARCHAR,D.SUB_OT)=CONSUMOS.SUB_OT
LEFT JOIN (SELECT SUB_OT,SUM(DECANTID)AS CANTIDAD FROM [BD_COSTOS].DBO.DETALLE_SERVICIOS  AS S INNER JOIN
(SELECT  DENUMDOC,DEITEM,DECODIGO,DEDESCRI,DECANTID,DEPRECIO FROM [010BDCOMUN].DBO.MOVINGDET_S) AS NI
ON S.NOTA_INGRESO=NI.DENUMDOC AND CAST(S.ITEM AS INT)=NI.DEITEM
GROUP BY SUB_OT)AS SERVICIOS ON  D.OT+'-'+CONVERT(VARCHAR,D.SUB_OT)=SERVICIOS.SUB_OT
WHERE CONVERT(VARCHAR,D.FECHA_FIN,23)  BETWEEN  '".$fechainicio."' AND '".$fechafin."'
";
$result = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
{
$dato[] = $fila;
}

return $dato;

}



function lista_costeo_acumuluado($fechainicio='',$fechafin='')
{
$conexion =  new Conexion();
$conexion -> sqlserver();
$query  =  "
SELECT D.OT,D.OT+'-'+CONVERT(VARCHAR,D.SUB_OT)AS SUB_OT,D.CODIGO,M.ADESCRI,D.NOTA_INGRESO,D.STATUS,D.TIPO_OT,D.TIPO_PROCESO,D.FECHA_INICIO,D.FECHA_FIN,
D.CANTIDAD,D.ENTREGA,D.SALDO,ISNULL(CONSUMOS.CANTIDAD,0) AS COSTO_TOTAL_CONSUMOS,
ISNULL(CONSUMOS.CANTIDAD,0)/ ISNULL(D.ENTREGA,0) AS COSTO_UNITARIO_CONSUMOS,
ISNULL(SERVICIOS.CANTIDAD,0) AS COSTO_TOTAL_SERVICIOS,
ISNULL(SERVICIOS.CANTIDAD,0)/ ISNULL(D.ENTREGA,0) AS COSTO_UNITARIO_SERVICIOS
FROM [BD_COSTOS].DBO.DETALLE_OT AS  D  
INNER JOIN  [010BDCOMUN].DBO.MAEART AS M ON
D.CODIGO=M.ACODIGO
LEFT JOIN (SELECT SUB_OT,SUM(DECANTID)AS CANTIDAD FROM [BD_COSTOS].DBO.DETALLE_CONSUMOS  AS DC INNER JOIN
(SELECT  DENUMDOC,DEITEM,DECODIGO,DEDESCRI,DECANTID,DEPRECIO FROM [010BDCOMUN].DBO.MOVALMDET WHERE DETD='NS' AND DEALMA='01') AS NS
ON DC.NOTA_SALIDA=NS.DENUMDOC AND DC.ITEM=NS.DEITEM
GROUP BY SUB_OT
)AS CONSUMOS  ON D.OT+'-'+CONVERT(VARCHAR,D.SUB_OT)=CONSUMOS.SUB_OT
LEFT JOIN (SELECT SUB_OT,SUM(DECANTID)AS CANTIDAD FROM [BD_COSTOS].DBO.DETALLE_SERVICIOS  AS S INNER JOIN
(SELECT  DENUMDOC,DEITEM,DECODIGO,DEDESCRI,DECANTID,DEPRECIO FROM [010BDCOMUN].DBO.MOVINGDET_S) AS NI
ON S.NOTA_INGRESO=NI.DENUMDOC AND CAST(S.ITEM AS INT)=NI.DEITEM
GROUP BY SUB_OT)AS SERVICIOS ON  D.OT+'-'+CONVERT(VARCHAR,D.SUB_OT)=SERVICIOS.SUB_OT
WHERE CONVERT(VARCHAR,D.FECHA_FIN,23)  BETWEEN  '".$fechainicio."' AND '".$fechafin."'
";
$result = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
{
$dato[] = $fila;
}

return $dato;

}




}

 ?>