<?php 


class Reporte
{


function __construct()
{

}



  function tipo_de_cambio()
    {
      
      $conexion =  new Conexion();
      $conexion -> sqlserver();
      $query  =  "SELECT * FROM ".BDCONTABILIDAD.".DBO.TIPO_CAMBIO";
      $result = mssql_query($query);
      while ($fila = mssql_fetch_assoc($result))
       {
      	  $dato[] = $fila;
       }

       return $dato;

    }




     function mano_de_obra()
    {
      
      $conexion =  new Conexion();
      $conexion -> sqlserver();
      $query  =  "SELECT UD.MES+'-'+UD.ANIO AS PERIODO,(ROW_NUMBER() OVER(ORDER BY TIPO_TRAB DESC,NOMBRES))AS ITEM,U.TIPO_TRAB,U.NOMBRES+' '+U.APELLIDOS AS NOMBRE,
U.CARGO,U.AREA,
UD.BASICO,UD.BONIFICACION_ORDINARIA,UD.BONIFICACION_VARIABLE,UD.BONIFICACION_NOCTURNA,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)AS TOTAL_INGRESOS,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.VACACIONES/100 AS VACACIONES,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.GRATIFICACIONES/100 AS GRATIFICACION,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.CTS/100 AS CTS,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.ESSALUD/100 AS ESSALUD,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.SCTR_PENSION/100 AS SCTR_PENSION,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.SCTR_SALUD/100 AS SCTR_SALUD,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.SCTR_VIDA/100 AS SCTR_VIDA,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.SENATI/100 AS SENATI,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)* UD.DESCANSO_MEDICO/100 AS DESCANSO_MEDICO,
UD.ASIGNACION_FAMILIAR  AS ASIGNACION_FAMILIAR,
(UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR AS COSTO_TOTAL_MENSUAL,
H.HORAS_HOMBRE AS HH_MES,
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR)/ H.HORAS_HOMBRE AS COSTO_HH_REAL,
(((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR)/ H.HORAS_HOMBRE)*1.25 AS COSTO_HE_25,
(((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR)/ H.HORAS_HOMBRE)*1.35 AS COSTO_HE_35,
(((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR)/ H.HORAS_HOMBRE)*2 AS COSTO_HE_100

 FROM ".BD.".dbo.USUARIOS  AS U
 INNER JOIN ".BD.".dbo.USUARIOS_DET  AS UD ON U.DNI=UD.DNI 
 INNER JOIN ".BD.".DBO.HOROMETRO AS H ON H.ANIO+H.MES=UD.ANIO+CAST(UD.MES AS INT) AND H.ACTIVAR=1
 WHERE U.TIPO=1";
      $result = mssql_query($query);
      while ($fila = mssql_fetch_assoc($result))
       {
          $dato[] = $fila;
       }

       return $dato;

    }



function costo_maquina()
{

$conexion =  new Conexion();
$conexion -> sqlserver();
$query  =  "SELECT MD.ANIO+'-'+MD.MES AS PERIODO,M.CODIGO_INTERNO,M.FECHA_ADQUISICION,M.FECHA_INICIO,M.CANTIDAD,M.FECHA_TERMINO,
MD.MES_DEPRECIADO,MD.MES_FALTANTE,M.CONTRATO_FACTURA,
M.DESCRIPCION,TM.DESCRIPCION AS TIPO,M.DESCRIPCION_ABRV,M.MODELO,M.SERIE,M.MARCA,
M.VALOR_CONTABLE,M.VALOR_CONTABLE / CR.TIEMPO_MES AS DEPRECIACION_MENSUAL,
(M.VALOR_CONTABLE / CR.TIEMPO_MES)* (MD.MES_DEPRECIADO) AS VALOR_DEPRECIADO_ACUMULADO,
(M.VALOR_CONTABLE) - ( (M.VALOR_CONTABLE / CR.TIEMPO_MES)* (MD.MES_DEPRECIADO) ) AS VALOR_ACTUAL,
H.HORAS_MAQUINA,
ISNULL(((((M.VALOR_CONTABLE) - ( (M.VALOR_CONTABLE / CR.TIEMPO_MES)* ( nullif(MD.MES_DEPRECIADO, 0)) ) ) / (nullif(MD.MES_FALTANTE, 0)))  / (H.HORAS_MAQUINA)),0) AS COSTO_HM_REAL
,(M.VALOR_CONTABLE / (CC.TIEMPO_MES*H.HORAS_MAQUINA)) AS COSTO_HM_COMERCIAL
 FROM [BD_COSTOS].DBO.MAQUINA AS M 
INNER JOIN ".BD.".DBO.MAQUINA_DET AS MD ON M.ID=MD.ID_MAQUINA 
INNER JOIN ".BD.".DBO.TIPO_MAQUINA  AS TM  ON M.ID_TIPO_MAQUINA=TM.ID
INNER JOIN ".BD.".DBO.HOROMETRO AS H ON MD.ANIO+CAST(MD.MES AS INT)= H.ANIO+H.MES AND H.ACTIVAR=1
INNER JOIN ".BD.".DBO.VIDA_UTIL_MAQUINA AS CC  ON H.ANIO+H.MES=CC.ANIO+CC.MES AND CC.TIPO=0  AND H.ACTIVAR=1 
INNER JOIN ".BD.".DBO.VIDA_UTIL_MAQUINA AS CR  ON H.ANIO+H.MES=CR.ANIO+CR.MES AND CR.TIPO=1  AND H.ACTIVAR=1 ";
$result = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
 {
    $dato[] = $fila;
 }

 return $dato;

}




function lista_servicios()
{
  $conexion =  new Conexion();
$conexion -> sqlserver();
$query  =  "
SELECT distinct CC.OC_CNUMORD'NUM.DOC',CC.OC_CNRODOCREF 'REQ',RESPONSABLE_NOMBRE 'RESPONSABLE',CC.OC_DFECDOC'FECHA.DOC',OC_CCODMON 'MONEDA',OC_NTIPCAM 'TC',OC_NIMPORT 'IMPORTE S/IGV',CC.OC_CCODPRO'RUC.PROVEE',CC.OC_CRAZSOC'RAZON.SOCIAL.PROVEE',OC_CFORPAG 'FORMA DE PAGO',
CASE CC.OC_CSITORD
WHEN '00' THEN 'EMITIDA'
WHEN '01' THEN 'APROBADA'
WHEN '03' THEN 'REQ PARCIAL'
WHEN '04' THEN 'REQ TOTAL'
WHEN '06' THEN 'ANULADA'
END 'EST COMPRA',DATEPART(WEEK,CC.OC_DFECDOC)AS SEMANA
FROM COMOVC_s  AS CC 

JOIN REQUISC R ON R.NROREQUI = CC.OC_CNRODOCREF and r.TIPOREQUI='rs'
JOIN (Select TCLAVE,TDESCRI from TABAYU  where TCOD= '12') T ON R.CODSOLIC=T.TCLAVE

join Responsablecmp on OC_CSOLICT=RESPONSABLE_CODIGO 
where CC.OC_DFECDOC BETWEEN '01-01-2017' AND '31-12-2017'";
$result = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
 {
    $dato[] = $fila;
 }

 return $dato;

}




function registro_diario($fechainicio,$fechafin,$tipo)
{

$conexion =  new Conexion();
$conexion -> sqlserver();
$query  =  "
SELECT D.ID,D.FECHA_TRABAJO,D.FECHA_PRODUCCION,D.HORA_INICIO,D.HORA_FIN,
D.HORAS_TRABAJO,D.HORAS_HOMBRE,D.DETALLE,D.OBSERVACION,D.OT,D.CANTIDAD_OT,D.TIPO,C.NOMBRE AS CLASIFICACION,P.NOMBRE AS PROCESOS,
M.CODIGO_INTERNO+' '+M.DESCRIPCION AS MAQUINA,T.CODIGO AS TURNO,
T.CODIGO,U.NOMBRES+ +U.APELLIDOS AS USUARIO
 FROM ".BD.".DBO.REGISTRO_DIARIO_DET AS D 
 LEFT JOIN  ".BD.".DBO.CLASIFICACION AS C  ON D.ID_CLASIFICACION=C.ID
 LEFT JOIN  ".BD.".DBO.PROCESOS AS P  ON D.ID_PROCESOS=P.ID
 LEFT JOIN  ".BD.".DBO.MAQUINA AS M  ON D.ID_MAQUINA=M.ID
 LEFT JOIN  ".BD.".DBO.TURNO AS T ON D.ID_TURNO=T.ID
 LEFT JOIN  ".BD.".DBO.USUARIOS AS U ON D.ID_USUARIO=U.ID
WHERE CONVERT(VARCHAR,D.FECHA_PRODUCCION,23)  BETWEEN '".$fechainicio."' AND '".$fechafin."' AND D.TIPO='".$tipo."'";
$result = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
 {
    $dato[] = $fila;
 }

 return $dato;

}









}




 ?>