<?php 


class Tiempos
{

function __construct()
{

}



function lista($fechainicio='',$fechafin='',$anio='',$mes='')
{
$conexion =  new Conexion();
$conexion -> sqlserver();
$query  =  "
SELECT D.ID,D.ID_USUARIO,D.FECHA_TRABAJO AS FECHA_DE_TRABAJO,D.FECHA_PRODUCCION AS FECHA_DE_PRODUCCION,
CASE D.TIPO
WHEN 1 THEN U.NOMBRES+' '+U.APELLIDOS
WHEN 2 THEN M.CODIGO_INTERNO+ +M.DESCRIPCION
END USUARIO_MAQUINA,ISNULL(M.CODIGO_INTERNO+' '+M.DESCRIPCION,'') AS MAQUINA,CONVERT(VARCHAR,D.HORA_INICIO,108) AS HORA_DE_INICIO,
CONVERT(VARCHAR,D.HORA_FIN,108) AS HORA_DE_FIN,D.HORAS_TRABAJO AS HORAS_TRABAJO,
D.HORAS_HOMBRE,D.OT,D.CANTIDAD_OT AS CANTIDAD_OT,T.CODIGO AS TURNO,
C.NOMBRE AS CLASIFICACION,P.NOMBRE AS PROCESO,C.ABRV AS CLASIFICACION_ABRV,
CASE P.FACTURABLE
WHEN 1 THEN 'SI'
WHEN 0 THEN 'NO'
ELSE 'VACIO'
END PROCESO_FACTURABLE,
CASE P.PRODUCTIVO
WHEN 1 THEN 'SI'
WHEN 0 THEN 'NO'
ELSE 'VACIO'
END PROCESO_PRODUCTIVO,
CASE C.ABRV  
WHEN 'REGULAR' THEN  ISNULL(HH.REGULAR,0)
WHEN 'HE25'    THEN  ISNULL(HH.HE_25,0)
WHEN 'HE35'    THEN  ISNULL(HH.HE_35,0)
WHEN 'HE100'   THEN  ISNULL(HH.HE_100,0)
ELSE 
ISNULL(HH.REGULAR,0)
END AS  COSTO_HH,
CASE C.ABRV  
WHEN 'REGULAR' THEN ISNULL(HH.REGULAR*D.HORAS_HOMBRE,0)
WHEN 'HE25'    THEN ISNULL(HH.HE_25*D.HORAS_HOMBRE,0)
WHEN 'HE35'    THEN ISNULL(HH.HE_35*D.HORAS_HOMBRE,0)
WHEN 'HE100'   THEN ISNULL(HH.HE_100*D.HORAS_HOMBRE,0)
ELSE 
ISNULL(HH.REGULAR*D.HORAS_HOMBRE,0)
END AS  COSTO_MO,
ISNULL(HM.COSTO_HM_REAL,0)AS COSTO_HMQ_REAL,
(ISNULL(HM.COSTO_HM_REAL,0))*D.HORAS_HOMBRE AS COSTO_MQ_REAL,
ISNULL(HM.COSTO_HM_COMERCIAL,0)AS COSTO_HMQ_COMERCIAL,
(ISNULL(HM.COSTO_HM_COMERCIAL,0))*D.HORAS_HOMBRE AS COSTO_MQ_COMERCIAL

FROM  ".BD.".DBO.REGISTRO_DIARIO_DET AS D
LEFT JOIN  ".BD.".DBO.TURNO AS T ON D.ID_TURNO=T.ID
LEFT JOIN  ".BD.".DBO.CLASIFICACION AS C ON D.ID_CLASIFICACION=C.ID
LEFT JOIN  ".BD.".DBO.PROCESOS AS P ON D.ID_PROCESOS=P.ID
LEFT JOIN  ".BD.".DBO.MAQUINA AS M ON D.ID_MAQUINA=M.ID
LEFT JOIN  ".BD.".DBO.USUARIOS AS U ON D.ID_USUARIO=U.ID
LEFT JOIN (SELECT U.ID,UD.MES+'-'+UD.ANIO AS PERIODO,U.NOMBRES+' '+U.APELLIDOS AS NOMBRE,
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR)/ H.HORAS_HOMBRE AS REGULAR,
(((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR)/ H.HORAS_HOMBRE)*1.25 AS HE_25,
(((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR)/ H.HORAS_HOMBRE)*1.35 AS HE_35,
(((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)+
((UD.BASICO+UD.BONIFICACION_ORDINARIA+UD.BONIFICACION_VARIABLE+
UD.BONIFICACION_NOCTURNA)*(UD.VACACIONES+UD.GRATIFICACIONES+UD.CTS+UD.ESSALUD+UD.SCTR_PENSION+UD.SCTR_SALUD+UD.SCTR_VIDA+UD.SENATI+UD.DESCANSO_MEDICO)/100)
+ UD.ASIGNACION_FAMILIAR)/ H.HORAS_HOMBRE)*2 AS HE_100,H.HORAS_HOMBRE,H.HORAS_MAQUINA
 FROM  ".BD.".dbo.USUARIOS  AS U
 INNER JOIN  ".BD.".dbo.USUARIOS_DET  AS UD ON U.DNI=UD.DNI AND U.TIPO=1
 INNER JOIN  ".BD.".DBO.HOROMETRO AS H ON H.ANIO+H.MES=UD.ANIO+CAST(UD.MES AS INT) AND H.ANIO='".$anio."' AND H.MES='".$mes."') AS HH
 ON U.ID=HH.ID
 LEFT JOIN (SELECT M.ID,M.CODIGO_INTERNO,
ISNULL(((((M.VALOR_CONTABLE) - ( (M.VALOR_CONTABLE / CR.TIEMPO_MES)* ( nullif(MD.MES_DEPRECIADO, 0)) ) ) / (nullif(MD.MES_FALTANTE, 0)))  / (H.HORAS_MAQUINA)),0) AS COSTO_HM_REAL
,(M.VALOR_CONTABLE / (CC.TIEMPO_MES*H.HORAS_MAQUINA)) AS COSTO_HM_COMERCIAL
 FROM  ".BD.".DBO.MAQUINA AS M 
INNER JOIN  ".BD.".DBO.MAQUINA_DET AS MD ON M.ID=MD.ID_MAQUINA 
INNER JOIN  ".BD.".DBO.TIPO_MAQUINA  AS TM  ON M.ID_TIPO_MAQUINA=TM.ID
INNER JOIN  ".BD.".DBO.HOROMETRO AS H ON MD.ANIO+CAST(MD.MES AS INT)= H.ANIO+H.MES AND H.ACTIVAR=1
INNER JOIN  ".BD.".DBO.VIDA_UTIL_MAQUINA AS CC  ON H.ANIO+H.MES=CC.ANIO+CC.MES AND CC.TIPO=0  AND H.ANIO='".$anio."' AND H.MES='".$mes."'
INNER JOIN  ".BD.".DBO.VIDA_UTIL_MAQUINA AS CR  ON H.ANIO+H.MES=CR.ANIO+CR.MES AND CR.TIPO=1  AND H.ANIO='".$anio."' AND H.MES='".$mes."') AS HM 
ON D.ID_MAQUINA=HM.ID
WHERE ISNULL(M.CODIGO_INTERNO,'')<>'VACÍO' AND D.TIPO=1  AND CONVERT(VARCHAR,D.FECHA_PRODUCCION,23) BETWEEN '".$fechainicio."'  AND '".$fechafin."'
";
$result = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
{
$dato[] = $fila;
}

return $dato;

}


function actualizar($id,$subot)
{

$conexion =  new Conexion();
$conexion -> sqlserver();
$query   =  "
UPDATE ".BD.".DBO.REGISTRO_DIARIO_DET SET SUB_OT='".$subot."' WHERE ID='".$id."' 
";
$result  = mssql_query($query);
if ($result) 
{
 return "ok";
}
else 
{
 return "error";
}

}



function agregar_subot($ot)
{

$conexion =  new Conexion();
$conexion -> sqlserver();
$query   =  "
SELECT OT+'-'+CONVERT(VARCHAR,SUB_OT) AS SUB_OT
 FROM ".BD.".DBO.DETALLE_OT WHERE OT='".$ot."'
";
$result  = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
{
$dato[] = $fila;
}

return $dato;

}

function actualizar_subot($ot,$subot)
{

$conexion =  new Conexion();
$conexion -> sqlserver();
$query   =  "
SELECT OT+'-'+CONVERT(VARCHAR,SUB_OT) AS SUB_OT
 FROM ".BD.".DBO.DETALLE_OT WHERE OT='".$ot."'  AND OT+'-'+CONVERT(VARCHAR,SUB_OT)<>'".$subot."'
";
$result  = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
{
$dato[] = $fila;
}

return $dato;

}


function lista_subot($id,$subot)
{

$conexion =  new Conexion();
$conexion -> sqlserver();
$query   =  "
SELECT  SUB_OT FROM ".BD.".DBO.REGISTRO_DIARIO_DET WHERE ID='".$id."'
 AND SUB_OT='".$subot."'
";
$result  = mssql_query($query);
while ($fila = mssql_fetch_assoc($result))
{
$dato[] = $fila;
}

return $dato;


}





function consulta($id,$campo)
{

$conexion =  new Conexion();
$conexion -> sqlserver();
$query   =  "
SELECT  * FROM ".BD.".DBO.REGISTRO_DIARIO_DET WHERE  ID='".$id."'
";
$result  = mssql_query($query);
$dato    = mssql_fetch_array($result);
return   $dato[$campo];

}



}



 ?>