CREATE TABLE DETALLE_OT
(

ID INT IDENTITY PRIMARY KEY,
OT VARCHAR(20),
CENTRO_COSTO VARCHAR(20),
SUB_OT INT,
CODIGO VARCHAR(25),
CANTIDAD NUMERIC(15,6),
ENTREGA NUMERIC(15,6),
SALDO    NUMERIC(15,6),
FECHA_INICIO SMALLDATETIME,
FECHA_FIN    SMALLDATETIME,
NOTA_INGRESO VARCHAR(20),
TIPO_ENTREGA VARCHAR(100),
STATUS VARCHAR(100),
TIPO_OT VARCHAR(100),
TIPO_PROCESO VARCHAR(100),
FECHA_CREACION SMALLDATETIME DEFAULT GETDATE()

)



CREATE TABLE DETALLE_SERVICIOS

(
ID INT IDENTITY,
OT VARCHAR(20),
SUB_OT VARCHAR(30),
NOTA_INGRESO VARCHAR(20),
ORDEN_SERVICIO VARCHAR(20),
FECHA_CREACION SMALLDATETIME DEFAULT GETDATE()

)


CREATE TABLE DETALLE_CONSUMOS
(

ID INT IDENTITY,
ITEM INT,
OT VARCHAR(20),
SUB_OT VARCHAR(30),
NOTA_SALIDA VARCHAR(20),
FECHA_CREACION SMALLDATETIME DEFAULT GETDATE()

)

CREATE TABLE HOROMETRO_DIARIO_MAQUINA
(

ID INT IDENTITY PRIMARY KEY,
FECHA SMALLDATETIME ,
ID_MAQUINA INT,
CANTIDAD_INICIAL NUMERIC(15,6),
CANTIDAD_FINAL   NUMERIC(15,6),
FECHA_CREACION SMALLDATETIME DEFAULT GETDATE()

)
